allow-dbg-in-tests = true
allow-expect-in-tests = true
allow-indexing-slicing-in-tests = true
allow-panic-in-tests = true
allow-unwrap-in-tests = true
allowed-duplicate-crates = [
  "bitflags",
  "convert_case",
  "core-foundation",
  "getrandom",
  "openssl-probe",
  "thiserror",
  "thiserror-impl",
  "wasi",
  "windows-link",
  "windows-sys",
  "windows-targets",
  "windows_aarch64_gnullvm",
  "windows_aarch64_msvc",
  "windows_i686_gnu",
  "windows_i686_gnullvm",
  "windows_i686_msvc",
  "windows_x86_64_gnu",
  "windows_x86_64_gnullvm",
  "windows_x86_64_msvc",
]
module-item-order-groupings = [
  ["extern_crate", ["extern_crate"]],
  ["imports", ["use"]],
  ["modules", ["foreign_mod", "mod"]],
  ["global_asm", ["global_asm"]],
  ["constants", ["const", "static"]],
  ["aliases", ["ty_alias"]],
  ["items", ["macro", "enum", "struct", "union", "trait", "trait_alias", "impl", "fn"]],
]
source-item-ordering = ["module"]
