[package]
name = "utils"
version = "0.1.0"
authors = ["Gian Lu"]
edition = "2021"

[features]
fake = ["dep:fake"]

[dependencies]
color-eyre = { workspace = true }
fake = { workspace = true, optional = true }
inquire = { version = "0.7" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { version = "2.0" }
url = { workspace = true }

[dev-dependencies]
assert2 = { version = "0.3" }
