[package]
name = "utils"
version = "0.1.0"
authors = ["Gian Lu"]
edition = "2024"

[features]
fake = ["dep:fake"]

[dependencies]
color-eyre = { workspace = true }
fake = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
skim = { version = "0.20" }
thiserror = { version = "2.0" }
url = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { version = "3" }
