[package]
name = "rua"
version = "0.1.0"
authors = ["Gian Lu"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
fkr = { path = "../fkr" }
mlua = { version = "0.11", features = ["macros", "module", "luajit"] }
strum = { workspace = true }
tree-sitter = { version = "0.25" }
tree-sitter-rust = { version = "0.24" }
utils = { path = "../utils" }
