[package]
name = "rua"
version = "0.1.0"
authors = ["Gian Lu"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.10", features = ["macros", "module", "luajit"] }
thiserror = { version = "1.0" }
