name: "Setup"
description: "Set up Rust toolchain & optionally install specified global cargo tools."
inputs:
  tools:
    description: "Comma-separated list of cargo crate specs (name or name@version)"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set up Rust (pinned nightly via rust-toolchain.toml)
      shell: bash
      working-directory: yog
      run: |
        set -euo pipefail
        rustup show
        rustc -V

    - name: Install global cargo tools
      if: inputs.tools != ''
      uses: taiki-e/install-action@v2
      with:
        tool: ${{ inputs.tools }}