[package]
name = "gcu"
version = "0.1.0"
authors = ["Gian Lu"]
edition = "2024"

[dependencies]
color-eyre = { workspace = true }
skim = { version = "0.20" }
url = { workspace = true }
utils = { workspace = true }
