[package]
name = "github"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Gian Lu"]

[dependencies]
cmd = { path = "../cmd" }
color-eyre = "0.6"
url = { version = "2.5", features = ["serde"] }

[dev-dependencies]
assert2 = { workspace = true }
