[package]
name = "github"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Gian Lu"]

[dependencies]
cmd = { path = "../cmd" }
color-eyre = { workspace = true }
url = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
