# Codecov configuration for yog workspace with per-crate components
# Reference: https://docs.codecov.com/docs/codecov-yaml
# Goals:
# - Per-crate component coverage (each workspace member = component)
# - Baseline overall targets (project default) retained
# - Patch coverage enforcement
# - Carry-forward + ignore rules preserved (paths corrected to actual layout)
# - Future: fine-tune thresholds per component once data stabilizes

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: 60..90

  status:
    project:
      # Overall workspace target
      default:
        target: 70%
        threshold: 2%
        informational: true
      # Per-component project statuses (initially same target; adjust later)
      catl: { target: 70%, threshold: 5%, informational: true }
      evoke: { target: 70%, threshold: 5%, informational: true }
      fkr: { target: 70%, threshold: 5%, informational: true }
      gch: { target: 70%, threshold: 5%, informational: true }
      gcu: { target: 70%, threshold: 5%, informational: true }
      ghl: { target: 70%, threshold: 5%, informational: true }
      idt: { target: 70%, threshold: 5%, informational: true }
      miskatonic: { target: 70%, threshold: 5%, informational: true }
      nomicon: { target: 70%, threshold: 5%, informational: true }
      nvrim: { target: 70%, threshold: 5%, informational: true }
      oe: { target: 70%, threshold: 5%, informational: true }
      tec: { target: 70%, threshold: 5%, informational: true }
      try: { target: 70%, threshold: 5%, informational: true }
      vpg: { target: 70%, threshold: 5%, informational: true }
      yghfl: { target: 70%, threshold: 5%, informational: true }
      yhfp: { target: 70%, threshold: 5%, informational: true }
      ytil_cmd: { target: 70%, threshold: 5%, informational: true }
      ytil_editor: { target: 70%, threshold: 5%, informational: true }
      ytil_git: { target: 70%, threshold: 5%, informational: true }
      ytil_github: { target: 70%, threshold: 5%, informational: true }
      ytil_hx: { target: 70%, threshold: 5%, informational: true }
      ytil_system: { target: 70%, threshold: 5%, informational: true }
      ytil_tui: { target: 70%, threshold: 5%, informational: true }
      ytil_wezterm: { target: 70%, threshold: 5%, informational: true }
    patch:
      default:
        target: 80%
        threshold: 2%
        informational: false
    changes:
      default:
        informational: true

  adjust:
    # Carry forward coverage for utility ytil crates so untouched code doesn't penalize patch metrics.
    - path: "yog/yog/ytil/"
      carryforward: true
    # Ignore template/generated sections (low signal for coverage)
    - path: "yog/yog/nomicon/src/templates/"
      ignore: true

# Ignore entire paths from all reports (non-Rust or generated assets)
ignore:
  - "yog/yog/nomicon/templates/"
  - "yog/yog/nomicon/assets/"
  - "yog/**/build.rs"

# Component definitions map crate directories to component IDs.
components:
  - component_id: catl
    paths: ["yog/yog/catl/"]
  - component_id: evoke
    paths: ["yog/yog/evoke/"]
  - component_id: fkr
    paths: ["yog/yog/fkr/"]
  - component_id: gch
    paths: ["yog/yog/gch/"]
  - component_id: gcu
    paths: ["yog/yog/gcu/"]
  - component_id: ghl
    paths: ["yog/yog/ghl/"]
  - component_id: idt
    paths: ["yog/yog/idt/"]
  - component_id: miskatonic
    paths: ["yog/yog/miskatonic/"]
  - component_id: nomicon
    paths: ["yog/yog/nomicon/"]
  - component_id: nvrim
    paths: ["yog/yog/nvrim/"]
  - component_id: oe
    paths: ["yog/yog/oe/"]
  - component_id: tec
    paths: ["yog/yog/tec/"]
  - component_id: try
    paths: ["yog/yog/try/"]
  - component_id: vpg
    paths: ["yog/yog/vpg/"]
  - component_id: yghfl
    paths: ["yog/yog/yghfl/"]
  - component_id: yhfp
    paths: ["yog/yog/yhfp/"]
  - component_id: ytil_cmd
    paths: ["yog/yog/ytil/cmd/"]
  - component_id: ytil_editor
    paths: ["yog/yog/ytil/editor/"]
  - component_id: ytil_git
    paths: ["yog/yog/ytil/git/"]
  - component_id: ytil_github
    paths: ["yog/yog/ytil/github/"]
  - component_id: ytil_hx
    paths: ["yog/yog/ytil/hx/"]
  - component_id: ytil_system
    paths: ["yog/yog/ytil/system/"]
  - component_id: ytil_tui
    paths: ["yog/yog/ytil/tui/"]
  - component_id: ytil_wezterm
    paths: ["yog/yog/ytil/wezterm/"]

comment:
  layout: "reach, diff, components, files"
  behavior: default
