local genghis = require("genghis")
vim.keymap.set("n", "<leader>yp", genghis.copyFilepath)
vim.keymap.set("n", "<leader>yn", genghis.copyFilename)
vim.keymap.set("n", "<leader>cx", genghis.chmodx)
vim.keymap.set("n", "<leader>rf", genghis.renameFile)
vim.keymap.set("n", "<leader>mf", genghis.moveAndRenameFile)
vim.keymap.set("n", "<leader>nf", genghis.createNewFile)
vim.keymap.set("n", "<leader>yf", genghis.duplicateFile)
vim.keymap.set("x", "<leader>x", genghis.moveSelectionToNewFile)
