[tools]
elixir = "latest"
elm = "latest"
erlang = "latest"
helm = "3.12.0"
java = "adoptopenjdk-18.0.1+10"
kubectl = "1.23.7"
node = "latest"
php = "8.1.26"
poetry = "latest"
protoc = "3.20.0"
python = "latest"
lua-language-server = "latest"

[settings]
experimental = true
