theme = "my_github_dark"

[editor]
auto-save = true
cursorline = true
rulers = [120]
shell = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["spinner", "file-modification-indicator", "diagnostics", "file-name"]
right = ["selections", "primary-selection-length", "workspace-diagnostics"]
mode.insert = "I"
mode.normal = "N"
mode.select = "S"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.whitespace.render]
nbsp = "all"
space = "all"
tab = "all"

[keys.insert]
C-b = ["move_prev_word_start"]
C-h = "move_char_left"
C-j = "move_line_down"
C-k = "move_line_up"
C-l = "move_char_right"
C-w = ["move_next_word_start"]

[keys.normal]
"C-d" = ["half_page_down", "goto_window_center"]
"C-e" = ":reset-diff-change"
"C-r" = ":reload-all"
"C-u" = ["half_page_up", "goto_window_center"]
"esc" = "keep_primary_selection"

[keys.normal.space]
F = "file_picker_in_current_buffer_directory"
W = ":write-all"
X = ":buffer-close-others"
q = ":quit-all"
w = ":write"
x = ":buffer-close"
