theme = "mine"

[editor]
auto-save = true
cursorline = true
rulers = [120]
shell = ["zsh", "-c"]
text-width = 120

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["spinner", "spacer", "file-modification-indicator", "spacer", "diagnostics", "file-name"]
right = ["selections", "primary-selection-length", "workspace-diagnostics"]
mode.insert = "I"
mode.normal = "N"
mode.select = "S"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.whitespace.render]
nbsp = "all"
space = "all"
tab = "all"

[keys.insert]
C-b = ["move_prev_word_start"]
C-h = ["move_char_left"]
C-j = ["move_line_down"]
C-k = ["move_line_up"]
C-l = ["move_char_right"]
C-w = ["move_next_word_start"]
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
A-b = ["move_prev_word_start"]
A-f = ["move_next_word_start"]
C-a = ["goto_line_start"]
C-e = ["goto_line_end"]
C-h = ["goto_previous_buffer"]
C-j = ["half_page_down", "goto_window_center"]
C-k = ["half_page_up", "goto_window_center"]
C-l = ["goto_next_buffer"]
D = ["delete_selection_noyank"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.";"]
S = [":pipe ccase -t screamingsnake", "delete_char_forward"]
c = [":pipe ccase -t camel", "delete_char_forward"]
k = [":pipe ccase -t kebab", "delete_char_forward"]
K = [":pipe ccase -t upperkebab", "delete_char_forward"]
l = [":pipe ccase -t lower", "delete_char_forward"]
p = [":pipe ccase -t pascal", "delete_char_forward"]
s = [":pipe ccase -t snake", "delete_char_forward"]
u = [":pipe ccase -t upper", "delete_char_forward"]

[keys.normal.space]
F = ["file_picker_in_current_buffer_directory"]
Q = [":quit-all!"]
U = [":reload-all"]
W = [":write!"]
X = [":buffer-close!"]
e = [":reset-diff-change"]
n = [":new"]
o = [":buffer-close-others"]
q = [":quit-all"]
u = [":reload"]
w = [":write"]
x = [":buffer-close"]

[keys.select]
C-j = ["half_page_down", "goto_window_center"]
C-k = ["half_page_up", "goto_window_center"]
D = ["delete_selection_noyank"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
