theme = "my_github_dark"

[editor]
auto-save = true
cursorline = true
line-number = "relative"
rulers = [120]

[editor.statusline]
center = ["version-control"]
left = ["mode", "spinner", "diagnostics", "file-modification-indicator", "file-name"]
mode.insert = "I"
mode.normal = "N"
mode.select = "S"
right = ["workspace-diagnostics", "selections", "position"]

[editor.lsp]
display-inlay-hints = true

[editor.whitespace.render]
nbsp = "all"
space = "all"
tab = "all"
