theme = "my_github_dark"

[editor]
auto-save = true
completion-replace = true
cursorline = true
rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["spinner", "file-modification-indicator", "file-name", "diagnostics"]
right = ["version-control", "selections", "primary-selection-length"]
mode.insert = "I"
mode.normal = "N"
mode.select = "S"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.whitespace.render]
nbsp = "all"
space = "all"
tab = "all"
