theme = "my_github_dark"

[editor]
auto-save = true
cursorline = true
rulers = [120]

[editor.file-picker]
hidden = false

[editor.statusline]
left = [
  "mode",
  "spinner",
  "diagnostics",
  "file-modification-indicator",
  "file-name",
]
right = ["version-control", "selections"]
mode.insert = "I"
mode.normal = "N"
mode.select = "S"

[editor.lsp]
display-inlay-hints = true

[editor.whitespace.render]
nbsp = "all"
space = "all"
tab = "all"
