theme = "my_gruvbox"

[editor]
auto-save = true
cursorline = true
insert-final-newline = true
rulers = [120]
shell = ["zsh", "-c"]
text-width = 120

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
git-global = false
git-ignore = false
hidden = false

[editor.statusline]
left = [
  "spinner",
  "spacer",
  "file-modification-indicator",
  "spacer",
  "diagnostics",
  "separator",
  "file-name",
  "separator",
]
right = [
  "selections",
  "primary-selection-length",
  "workspace-diagnostics",
  "position",
]
mode.insert = "I"
mode.normal = "N"
mode.select = "S"
separator = '`'

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.whitespace.render]
nbsp = "all"
space = "all"
tab = "all"

[keys.insert]
A-b = ["move_prev_word_start"]
A-f = ["move_next_word_start"]
C-a = ["goto_first_nonwhitespace"]
C-b = ["move_prev_word_start"]
C-e = ["goto_line_end"]
C-w = ["move_next_word_start"]
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
'/' = ["search_selection", "search"]
A-b = ["move_prev_word_start"]
A-f = ["move_next_word_start"]
C-d = ["half_page_down", "goto_window_center"]
C-l = [":sh weh gh"]
C-r = [":lsp-restart"]
C-u = ["half_page_up", "goto_window_center"]
D = ["delete_selection_noyank"]
F = ["search_selection", "global_search"]
X = ["extend_line_up", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.";"]
S = [":pipe ccase -t screamingsnake", "delete_char_forward"]
c = [":pipe ccase -t camel", "delete_char_forward"]
k = [":pipe ccase -t kebab", "delete_char_forward"]
K = [":pipe ccase -t upperkebab", "delete_char_forward"]
l = [":pipe ccase -t lower", "delete_char_forward"]
p = [":pipe ccase -t pascal", "delete_char_forward"]
s = [":pipe ccase -t snake", "delete_char_forward"]
u = [":pipe ccase -t upper", "delete_char_forward"]

[keys.select.";"]
S = [":pipe ccase -t screamingsnake", "delete_char_forward"]
c = [":pipe ccase -t camel", "delete_char_forward"]
k = [":pipe ccase -t kebab", "delete_char_forward"]
K = [":pipe ccase -t upperkebab", "delete_char_forward"]
l = [":pipe ccase -t lower", "delete_char_forward"]
p = [":pipe ccase -t pascal", "delete_char_forward"]
s = [":pipe ccase -t snake", "delete_char_forward"]
u = [":pipe ccase -t upper", "delete_char_forward"]

[keys.normal.space]
F = ["file_picker_in_current_buffer_directory"]
Q = [":quit-all!"]
U = [":reload-all"]
W = [":write!"]
X = [":buffer-close!"]
e = [":reset-diff-change"]
n = [":new"]
o = [":buffer-close-others"]
q = [":quit-all"]
space = [":write"]
u = [":reload"]
x = [":buffer-close"]

[keys.select]
C-d = ["half_page_down", "goto_window_center"]
C-l = [":sh weh gh"]
C-r = [":lsp-restart"]
C-u = ["half_page_up", "goto_window_center"]
D = ["delete_selection_noyank"]
F = ["search_selection", "global_search"]
X = ["extend_line_up", "extend_to_line_bounds"]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
f = ["search_selection", "search"]
