use-grammars = { only = ["rust", "elm", "toml", "json", "yaml", "bash"] }

[[language]]
name = "rust"
config.check.command = "clippy"
config.checkOnSave.command = "clippy"
config.completion.autoimport.enable = true
config.imports.granularity.enforce = true
config.imports.granularity.group = "item"
config.imports.prefix = "crate"
config.lens.debug.enable = false
config.lens.implementations.enable = false
config.lens.run.enable = false
config.showUnlinkedFileNotification = false

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "python"
auto-format = true
config.pylsp.plugins.ruff = { enabled = true, lineLength = 120 }

[[language]]
name = "bash"
auto-format = true

[[language]]
name = "yaml"
auto-format = true

[[language]]
name = "json"
auto-format = true

[[language]]
name = "markdown"
auto-format = true

[[language]]
name = "lua"
auto-format = true
