use-grammars = { only = ["rust", "toml", "elm", "json", "lua", "python", "bash", "yaml", "markdown"] }

[[language]]
name = "rust"
config.check.command = "clippy"
config.checkOnSave.command = "clippy"
config.completion.autoimport.enable = true
config.imports.granularity.enforce = true
config.imports.granularity.group = "item"
config.imports.prefix = "crate"
config.lens.debug.enable = false
config.lens.implementations.enable = false
config.lens.run.enable = false
config.showUnlinkedFileNotification = false
config.cargo.extraArgs = ["--profile", "rust-analyzer"]
config.cargo.extraEnv = { "CARGO_PROFILE_RUST_ANALYZER_INHERITS" = "dev" }

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "elm"
auto-format = true

[[language]]
name = "json"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "lua"
auto-format = true

[[language]]
name = "python"
auto-format = true
config.pylsp.plugins.ruff = { enabled = true, lineLength = 120 }

[[language]]
name = "bash"
auto-format = true

[[language]]
name = "yaml"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "yaml"] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "markdown"] }

[[language]]
name = "html"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "css"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
