[package]
name = "nomicon"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Generate a consolidated styled workspace documentation."
keywords = ["docs", "documentation", "html", "generator"]
categories = ["command-line-utilities", "development-tools"]
build = "build.rs"

[package.metadata.cargo-machete]
ignored = ["lightningcss"]

[[bin]]
name = "nomicon-server"
path = "src/server.rs"

[dependencies]
askama = { version = "0.14" }
axum = { version = "0.8" }
chrono = { workspace = true }
color-eyre = { workspace = true }
shuttle-axum = { version = "0.57" }
shuttle-runtime = { version = "0.57" }
ytil_cmd = { workspace = true }
ytil_system = { workspace = true }

[build-dependencies]
color-eyre = { workspace = true }
lightningcss = { version = "1.0.0-alpha.68", default-features = false, features = [
  "browserslist",
] }
