[package]
name = "tempura"
version = "0.1.0"
authors = ["Gian Lu"]
edition = "2021"

[dependencies]
anyhow = { version = "1.0.79", features = ["backtrace"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
url = { version = "2.5.0", features = ["serde"] }

[dev-dependencies]
fake = { version = "2.9", features = ["derive"] }
temp-env = { version = "0.3.6" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
