require('config.opts')
require('config.keymaps')
require('config.packer')
require('config.colorscheme')
require('config.telescope')
require('config.gitsigns')
require('config.auto-save')
require('config.treesitter')
require('config.lsp')
require('config.nvim-tree')
require('config.mason')

local genghis = require("genghis")
vim.keymap.set("n", "<leader>yp", genghis.copyFilepath)
vim.keymap.set("n", "<leader>yn", genghis.copyFilename)
vim.keymap.set("n", "<leader>cx", genghis.chmodx)
vim.keymap.set("n", "<leader>rf", genghis.renameFile)
vim.keymap.set("n", "<leader>mf", genghis.moveAndRenameFile)
vim.keymap.set("n", "<leader>nf", genghis.createNewFile)
vim.keymap.set("n", "<leader>yf", genghis.duplicateFile)
vim.keymap.set("x", "<leader>x", genghis.moveSelectionToNewFile)
