require('config.opts')
require('config.keymaps')
require('config.packer')
require('config.colorscheme')
require('config.telescope')
require('config.gitsigns')
require('config.auto-save')
require('config.treesitter')
require('config.lsp')
require('config.nvim-tree')
require('config.mason')

local keymap = vim.keymap.set
local genghis = require("genghis")
keymap("n", "<leader>yp", genghis.copyFilepath)
keymap("n", "<leader>yn", genghis.copyFilename)
keymap("n", "<leader>cx", genghis.chmodx)
keymap("n", "<leader>rf", genghis.renameFile)
keymap("n", "<leader>mf", genghis.moveAndRenameFile)
keymap("n", "<leader>nf", genghis.createNewFile)
keymap("n", "<leader>yf", genghis.duplicateFile)
keymap("x", "<leader>x", genghis.moveSelectionToNewFile)
