[workspace]
resolver = "2"
members = ["src/*"]

[profile.test]
# Reduces the size of the target directory
debug = false

[profile.release]
# Reduces the size of the target directory
strip = true
lto = true
codegen-units = 1
panic = "abort"
