inherits = "github_dark"

"comment" = { modifiers = ["italic"] }
"ui.cursor" = { fg = "black", bg = "white" }
"ui.cursor.match" = { fg = "black", bg = "scale.orange.2" }
"ui.virtual.inlay-hint" = { fg = "gray" }
"ui.virtual.ruler" = { bg = "canvas.subtle" }
