[package]
name = "system"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Gian Lu"]

[dependencies]
cmd = { path = "../cmd" }
color-eyre = { workspace = true }
chrono = { workspace = true }
