[package]
name = "vpg"
version = "0.1.0"
authors = ["Gian Lu"]
edition = "2024"

[dependencies]
color-eyre = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utils = { workspace = true }
