[package]
name = "ytil_github"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Query GitHub refs, URLs, and repository metadata."
keywords = ["github", "api", "repository", "refs", "cli"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
chrono = { workspace = true }
color-eyre = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
url = { workspace = true }
ytil_cmd = { workspace = true }
ytil_git = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
rstest = { workspace = true }
