[package]
name = "hx"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Gian Lu"]

[features]
fake = ["dep:fake"]

[dependencies]
color-eyre = "0.6"
fake = { version = "4.4", features = ["derive"], optional = true }

[dev-dependencies]
fake = { version = "4.4", features = ["derive"] }
