enter_accept = true
exit_mode = "return-query"
history_format = "{time} | {command}"
inline_height = 12
prefers_reduced_motion = true
search_mode = "fuzzy"
secrets_filter = true
show_help = false
show_preview = true
show_tabs = false
style = "compact"

[preview]
strategy = "static"
