[package]
name = "weh"
version = "0.1.0"
authors = ["Gian Lu"]
edition = "2021"

[dependencies]
anyhow = { version = "1.0.75", features = ["backtrace"] }
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.17"
url = { version = "2.4.1", features = ["serde"] }

[dev-dependencies]
fake = { version = "2.8", features = ["derive"] }
temp-env = { version = "0.3.6" }
