[package]
name = "ytil_system"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
description = "Work with system paths, time, clipboard, and files."
keywords = ["system", "time", "io", "environment", "platform"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
chrono = { workspace = true }
color-eyre = { workspace = true }
ytil_cmd = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
tempfile = "3.13"
