[package]
name = "fkr"
version = "0.1.0"
authors = ["Gian Lu"]
edition = "2021"

[dependencies]
color-eyre = { workspace = true }
fake = { workspace = true, features = ["uuid"] }
strum = { workspace = true }
utils = { workspace = true }
