name: Doc

on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "yog/**"

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.ref }}-doc
  cancel-in-progress: true

jobs:
  build:
    name: Build & publish doc
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build Rust doc
        working-directory: yog
        run: |
          cargo doc --all --no-deps --document-private-items

      - name: Clean stale root doc index
        working-directory: yog
        run: rm -f target/doc/index.html || true

      - name: Add Cargo root redirect to crate docs
        working-directory: yog
        run: |
          echo "<meta http-equiv=\"refresh\" content=\"0;url=yog/index.html\">" > target/doc/index.html

      - name: Upload Rust doc as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: yog/target/doc

      - name: Deploy Rust doc artifact to GitHub Pages
        uses: actions/deploy-pages@v4
