name: Doc

on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "yog/**"

env:
  CARGO_TERM_COLOR: always
  RUSTC_WRAPPER: sccache
  SCCACHE_DIR: /home/runner/.cache/sccache
  SCCACHE_CACHE_SIZE: 3G
  SCCACHE_FAIL_FAST: "1"

concurrency:
  group: ${{ github.ref }}-doc
  cancel-in-progress: true

jobs:
  build:
    name: Build & publish doc
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: yog
          shared-key: docs
          cache-targets: true

      - name: sccache setup
        uses: ./.github/actions/sccache
        with:
          cache-key-suffix: docs
          cache-size: 3G

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build Rust doc with nomicon
        working-directory: yog
        run: |
          cargo run --bin nomicon

      - name: sccache post stats
        if: always()
        uses: ./.github/actions/sccache-post-stats
        with:
          label: Docs

      - name: Upload Rust doc as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: yog/target/doc

      - name: Deploy Rust doc artifact to GitHub Pages
        uses: actions/deploy-pages@v4
