name: Doc

on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
      - "yog/**"

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.ref }}-doc
  cancel-in-progress: true

jobs:
  build:
    name: Build & publish doc
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build Rust doc
        run: |
          cd yog
          cargo doc --all --no-deps --document-private-items

      # https://www.reddit.com/r/rust/comments/195ao81/comment/khm4xqa/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
      - name: Add doc root index.html with redirect to 1st bin doc
        run: echo '<meta http-equiv="refresh" content="0;url=catl/index.html">' > yog/target/doc/index.html

      - name: Upload Rust doc as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: yog/target/doc

      - name: Deploy Rust doc artifact to GitHub Pages
        uses: actions/deploy-pages@v4
