[package]
name = "inquire"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["Gian Lu"]

[dependencies]
color-eyre = { workspace = true }
inquire = { version = "0.7", features = ["fuzzy-matcher"] }
strum = { workspace = true }
