[tools]
elm = "latest"
helm = "3.12.0"
kubectl = "1.23.7"
node = "lts"
poetry = "latest"
protoc = "25.0"
python = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["rust"]
